######################## default configuration ####################
baseURL = "https://amordeorigen.com"
languageCode = "en-us"
title = "Amor De Origen"
theme = "icelab-hugo"
summaryLength = "10"


############################## Output ###############################
[outputs]
home = ["HTML", "RSS"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################## Output ###############################
# JS Plugins
[[params.plugins.js]]
URL = "plugins/plugins.js"


############################## navigation ###########################
[[menu.main]]
name = "Nosotros"
URL = "nosotros"
weight = 2

[[menu.main]]
name = "Productos"
URL = "productos"
weight = 3

[[menu.main]]
name = "Contacto"
URL = "contacto"
weight = 4


#################### default parameters ##############################
[params]
logo = "images/logo.png"
home = "Inicio"
# Meta data
description = ""
author = ""
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# footer content
footer_content = "@ 2023 *Amor De Origen.* <br>Todos Los Derechos Reservados."

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social site ########################
#[[params.social]]
# name = "facebook"
# icon = "fa-facebook" # fontawesome icon pack v4.7
# link = "#"

#[[params.social]]
#name = "twitter"
#icon = "fa-twitter" # fontawesome icon pack v4.7
#link = "#"

[[params.social]]
name = "instagram"
icon = "fa-instagram" # fontawesome icon pack v4.7
link = "https://www.instagram.com/cafeamordeorigen"

[[params.social]]
name = "email"
icon = "fa-regular fa-envelope" # fontawesome icon pack v4.7
link = "mailto:cafeamordeorigen@gmail.com"

